### ISSUE TITLE
logout, register

### ISSUE THREAD

**Issue by melaniechow** [ecrowdus/swconstruction-events#22]
I think it's better to have logout, currently I don't know how to terminate the app.  2. when registering a new account, A. if my input is wrong, it only shows "invalid entry", if it can show more concrete information, it would be great, like "email address is wrong" (it's same for profile editing). B. when successfully register, the user will be directed to the login page. If the user clicks "register" again, every information that the user used for the register is shown (including password), it leaks the user's information.

**Comment by khe618** [comment]
So I don't believe there is any validation on the backend (which could change), so I suspect this is maybe due to the password/username requirements on the front end?
