### ISSUE TITLE
Sort events in feed view

### ISSUE THREAD

**Issue by melaniechow** [ecrowdus/swconstruction-events#23]
4. Even for a new user, there will be some events showing in the explore page, I am just curious how you will decide what to show for a new user. I just have a sense you display all events from your database, then what if you have thousands of events? 

I think you need to somehow sort all the events Currently, newly-created events will always be the last one on your explore page, which may not be ideal. Maybe you can sort based on hot level or start date?.

**Comment by khe618** [comment]
The events are currently sorted by hot level, then by distance, then by time, and is limited in distance to a set radius

**Comment by melaniechow** [comment]
actually the endpoint needs to be changed
