### ISSUE TITLE
Not intuitive to create user

### ISSUE THREAD

**Issue by melaniechow** [ecrowdus/swconstruction-events#8]
1) had issue creating the user:

username: abc1
firstname: Melanie
lastname: Chow
email: Abc@gmail.com
pass: Abc1!

2) didnt get good feedback on why my user was not being created properly

3) requirements abt username and password should be outside

4) i dont think username should require a number

5) should probably figure out how to make the 'dots' with the password (passowrd concealer thingy)

**Comment by katherinehli** [comment]
resolved 1-5
