### ISSUE TITLE
Can access all pages when not logged in

### ISSUE THREAD

**Issue by melaniechow** [ecrowdus/swconstruction-events#9]
So if i swipe to the left, I can still access the other pages, but they will all break because user is not defined bc i didnt go through login. Also, the registration form should have a button to be like "Already have an account?" or like "Log in" link so I can go to the login page

**Comment by crowdus** [comment]
@jiayilin-286 @katherinehli @rrauber can we split this issue up?
ross and I can handle accessing the menu from log-in, and katherine and jiayi, you all can handle differentiating between log in / create account ?

**Comment by rrauber** [comment]
Fixed!

**Comment by rrauber** [comment]
Added a back button to the login page as well.
